theme = "native"
# icons = "none"
icons = "awesome5"

[[block]]
block = "sound"
format = "{volume}"

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"
display_type = "memory"
clickable = true
icons = true
interval = 5

[[block]]
block = "backlight"
device = "intel_backlight"
invert_icons = true

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "time"
format = "%a %b %d, %Y %R"
timezone = "US/Pacific"
