[theme]
theme = "native"
# theme = "plain"

[icons]
icons = "material-nf"

[[block]]
block = "music"
format = " $icon {$combo.str(0,20) $play |}"

[[block]]
block = "sound"
# format = "$icon $volume"

[[block]]
block = "memory"
display_type = "memory"
# format_mem = "$icon $mem_free.eng(3,B,M)/$mem_total.eng(3,B,M)($mem_total_used_percents.eng(2))"
format_mem = "$icon $mem_used_percents.eng(2) "
# format_swap = "$icon $swap_used_percents.eng(2) "

[[block]]
block = "cpu"
interval = 1
format = " $icon  $barchart.str() $utilization.eng() "
format_alt = "$icon $frequency.eng(){ $boost.str()|} "

[[block]]
block = "backlight"
device = "intel_backlight"
# format = "$icon $brightness"
invert_icons = true

[[block]]
block = "battery"
format = " $icon $percentage "
# driver = "sysfs"
# device = "BAT0"

[[block]]
block = "time"
format = " %a %b %d, %Y %R "
timezone = "US/Pacific"
